### ISSUE TITLE
[Crash]: Configured Defaults crashes on Fabric server startup when trying to write log message

### ISSUE THREAD

**Issue by s-thom** [Fuzss/configureddefaults#1]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.4

### Mod Version (Required)

v8.0.1

### Notes (Required)

1. Set up [Fabric server](https://meta.fabricmc.net/v2/versions/loader/1.20.4/0.15.7/1.0.0/server/jar) with [Configured Defaults](https://cdn.modrinth.com/data/SISoSFPP/versions/hOcrPrzr/ConfiguredDefaults-v8.0.1-1.20.1-Fabric.jar) as the only mod.
2. Start server.
3. Observe server crashing immediately after creating the `configureddefaults` directory.

Following the stack trace, it appears to be because [`gamePath.getParent()`](https://github.com/Fuzss/configureddefaults/blob/52805286f845a0798ae622237f24f7f311df389d/1.20/Common/src/main/java/fuzs/configureddefaults/handler/CopyDefaultsHandler.java#L50) is returning null. I have been able to reproduce on other 1.20.* versions of Minecraft, and with a similar error on Configured Defaults 8.0.0 (though the exact lines of code changed). The client doesn't seem to have this crash issue.

### Crash Report (Required)

https://gist.github.com/s-thom/07d4ac042a54d43e5f31e81f63c3371e

**Comment by Fuzss** [comment]
Fixed, thank you!
