### ISSUE TITLE
[Bug]: Latest version causes MC to fail to launch on Fabric, but not Quilt

### ISSUE THREAD

**Issue by rydens** [Fuzss/configureddefaults#3]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

v8.0.2

### Notes (Required)

Hello! Not exactly a crash, but Minecraft does [fail to start with just ConfiguredDefaults installed with Fabric.](https://mclo.gs/WvWpYis)  This doesn't occur on Quilt, nor on the previous v8.0.1 version.

### latest.log (Required)

https://mclo.gs/WvWpYis

**Comment by Fuzss** [comment]
Thanks, does the new v8.0.3 help with that?

**Comment by Fuzss** [comment]
Did some testing and this seems to fix it. Please reopen if the issue comes back!
