### ISSUE TITLE
[Crash]: Version v21.1.1-1.21.1 Crashes On Bootup

### ISSUE THREAD

**Issue by LordOfTheWeebs** [Fuzss/configureddefaults#4]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21.1

### Mod Version(s) (Required)

21.1.1

### Notes (Required)

1. Add v21.1.1-1.21.1 to instance.
2. Launch

(Launch does not create a crash report, only a latest.log, hence why the latest.log is the crash report)

### Crash Report (Required)

https://gist.github.com/LordOfTheWeebs/089e722e3f1f7c999536a7ca1f0fac72

**Comment by Fuzss** [comment]
Should be fixed now, thanks for reporting!
